model_params:
  name: 'VAE3D'
  in_channels: 1
  latent_dim: 128
  hidden_dims: [64, 128, 256, 512]

exp_params:
  dataset: MNISTB
  data_path: "/Users/ronose/Documents/Lab/Research/Data/mnistb/data_vox.npy"
  img_size: 32
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_nb_epochs: 20
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: "MNISTB"
  manual_seed: 1265
