model_params:
  name: 'VanillaVAE'
  in_channels: 16
  latent_dim: 128

exp_params:
  dataset: VOL
  # data_path: "/Users/ronose/Documents/Lab/Research/Data"
  data_path: "/Users/ronose/Documents/Lab/Repo/pmat-generator-toolkit/tests/test_volume_16ch_norm.npy"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
