model_params:
  name: 'VQVAE'
  in_channels: 4
  #   embedding_dim: 64
  #   num_embeddings: 512
  embedding_dim: 64
  num_embeddings: 32
  img_size: 32
  beta: 0.25
  res_num: 1
  #   hidden_dims: [128, 256]

exp_params:
  dataset: MNISTB
  data_path: "/home/onose/shared/Data/mnistb/data_vox01_5919b4c64w64h.npy"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.0001
  # LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: 1
  max_nb_epochs: 30
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VQVAE_MNISTB"
  manual_seed: 1265
