model_params:
  name: 'VQVAE'
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25
  res_num: 6

exp_params:
  dataset: CIFAR10
  data_path: "/home/onose/shared/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VQVAE_CIFAR"
  manual_seed: 1265
