model_params:
  name: 'VQVAE3D'
  in_channels: 1
  embedding_dim: 512
  num_embeddings: 1024
  img_size: 32
  beta: 0.25
  res_num: 6
  hidden_dims: [256, 512]

exp_params:
  dataset: MNISTB
  data_path: "/home/onose/shared/Data/mnistb/data_vol_5907b1c16d16w16h.npy"
  img_size: 32
  batch_size: 144 # Better to have a square number
  LR: 0.00001
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "VQVAE3D_MNISTB"
  manual_seed: 1265
